Add : SignUp_ui
hyejin30/WebRTC-APPLICATION-Frontend pull request #1
Opened 2022-03-30 01:00 UTC by hyejin30

## :: 구현 목표 
* SignUp 페이지 ui 구현

<br />

## :: 구현 사항 설명
* header, 뒤로가기 아이콘을 제외하고 먼저 구현 했습니다.
* 아래 디바이스를 기준으로 작업
* aos : Nexus 5
* ios : iPhone 13

<img width="849" alt="image" src="https://user-images.githubusercontent.com/98295004/160729808-03adec26-ed4b-4a52-98db-4331daf698c7.png">

<br />

## :: 기타 질문 및 특이 사항

1. 브랜치 세분화
- 아래처럼 나누어서 하려고 하는데 적절할지
- ui : feature/signup_ui
- 유효성 검사 : feature/signup_validation

2. 디바이스 선택
- 어떤 디바이스를 기준으로 선택하고 ui 작업하면 좋을지 궁금합니다.

3. OS별 스타일링
- android가 조금 깨지는데, android, ios 각각 스타일링 해야할지 궁금합니다.

4. header
- 직접 View로 만들어야 할지 or headerShown: true로 하고 커스텀 해야할지 궁금합니다.

<br />

2022-03-30 01:27 UTC, Enjoywater commented
1. 제 생각에는 **feature/signup**으로 해도 괜찮을 것 같습니다. 커밋으로 나눌 수 있는 부분인 것 같고, 너무 많은 pr이 생성될 것 같습니다.
2. 여러개의 모든 디바이스를 테스트해볼 수는 없기 때문에 현재 선택하신 디바이스로 해도 괜찮습니다.
3. OS별로 스타일이 다르게 적용되는 부분들이 있습니다. **OS를 판별**해서 OS에 맞는 스타일을 적용할 수 있습니다.
4. 어느 것을 사용해도 괜찮겠지만, 기본 헤더를 사용하다가 **한계를 느끼는 부분**이 있다면 커스텀 헤더로 바꾸셔도 됩니다.
5. **css-in-js**를 사용하는 것을 추천드립니다.

2022-03-31 07:51 UTC, Enjoywater commented on src/hooks/hooks.ts
> +        password: signUpInfo.password,
**구조분해 및 단축속성**을 사용하면 간결하게 작성이 가능합니다.

2022-03-31 07:51 UTC, Enjoywater commented on src/pages/SignUp.tsx
> +    last_name: '',
**camel case**를 사용해주세요

2022-03-31 07:51 UTC, Enjoywater commented on src/pages/SignUp.tsx
> +      console.log(result);
**push**하기 전에는 **console**을 확인해주세요!

2022-03-31 07:51 UTC, Enjoywater commented on src/pages/SignUp.tsx
> +  const eyeOnIcon = require('../assets/images/ic-feather-eye-on.png');
`images`폴더 내부에서 `index`파일로 이미지를 한번에 관리할 수 있습니다.

2022-03-31 07:51 UTC, Enjoywater commented on src/pages/SignUp.tsx
> +                  value={signUpInfo.first_name}
상단에 **구조분해**가 된 값으로 `value`를 넣어줄 수 있을 것 같습니다.

2022-03-31 07:57 UTC, Enjoywater commented on src/pages/SignUp.tsx
> +  const {first_name, last_name, email, password, passwordVerify} = signUpInfo;
**구조분해**를 해놓은 값이 **camel case**가 아니라면 [링크](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#%EC%83%88%EB%A1%9C%EC%9A%B4_%EB%B3%80%EC%88%98_%EC%9D%B4%EB%A6%84%EC%9C%BC%EB%A1%9C_%ED%95%A0%EB%8B%B9%ED%95%98%EA%B8%B0) 처럼 변경해서 사용이 가능합니다.

2022-03-31 08:21 UTC, hyejin30 commented on src/pages/SignUp.tsx
> +      console.log(result);
넵 push 전에는 console.log 모두 삭제하겠습니다!

2022-03-31 13:50 UTC, hyejin30 commented on src/hooks/hooks.ts
> +        password: signUpInfo.password,
적용해서 작성하겠습니다! 감사합니다

2022-03-31 13:51 UTC, hyejin30 commented on src/pages/SignUp.tsx
> +    last_name: '',
camel case로 통일하겠습니다!

2022-03-31 13:52 UTC, hyejin30 commented on src/pages/SignUp.tsx
> +  const eyeOnIcon = require('../assets/images/ic-feather-eye-on.png');
이미지 관리가 고민이었는데 감사합니다!! 적용하겠습니다

2022-03-31 13:52 UTC, hyejin30 commented on src/pages/SignUp.tsx
> +                  value={signUpInfo.first_name}
구조분해 적용하겠습니다!

2022-03-31 13:53 UTC, hyejin30 commented on src/pages/SignUp.tsx
> +  const {first_name, last_name, email, password, passwordVerify} = signUpInfo;
참고글도 함께 안내해주셔서 감사합니다! 적용하겠습니다

2022-03-31 16:43 UTC, hyejin30 commented on src/pages/SignUp.tsx
> +  const {first_name, last_name, email, password, passwordVerify} = signUpInfo;
서버 키 값이 first_name, last_name인 점을 고려해서
새로운 변수명을 snake case로 지정했습니다

```
  const {
    firstName: first_name,
    lastName: last_name,
    email,
    password,
  } = signUpInfo;
  ...
  body: JSON.stringify({
        email,
        first_name,
        last_name,
        password,
      }),
```

2022-03-31 16:45 UTC, hyejin30 commented on src/hooks/hooks.ts
> +        password: signUpInfo.password,
signUpInfo의 key는 모두 camel case로 변경했고,
서버 키가 first_name, last_name인 점을 고려해서
POST 요청을 보낼 때만 새로운 변수명을 snake case로 지정했습니다

```
  const {
    firstName: first_name,
    lastName: last_name,
    email,
    password,
  } = signUpInfo;
  
  ...
  
  body: JSON.stringify({
        email,
        first_name,
        last_name,
        password,
      }),
```

2022-04-01 01:04 UTC, hyejin30 commented on src/hooks/hooks.ts
> +        password: signUpInfo.password,
snake_case로 변경하지 않고 camel case 그대로 사용하도록 수정했습니다!

```
  const {firstName, lastName, email, password} = signUpInfo;
 
 ...
 
 body: JSON.stringify({
        email,
        first_name: firstName,
        last_name: lastName,
        password,
      }),
```

2022-04-01 04:49 UTC, Enjoywater commented on src/components/LabelPwInput.tsx
> +
공백은 제거해주세요

2022-04-01 04:57 UTC, LEEYEONSEONG requested changes

2022-04-01 04:57 UTC, LEEYEONSEONG commented on src/pages/SignUp.tsx
> +import {LabelInput} from '../components/LabelInput';
compoenent 파일 내에 index 파일을 만들어 관리해 주시면 좋습니다.
`export { default as LabeInput } from "./LabelInput"`

2022-04-01 04:58 UTC, Enjoywater commented on src/config.ts
> +const baseUri: String = 'http://172.30.1.30:8080';
외부로 노출이 되면 안되는 데이터들은 `.env` 파일을 만들고 관리해주세요

2022-04-01 05:04 UTC, Enjoywater commented on src/assets/images/index.ts
> +export default Images;
이미지 파일 분리가 잘 되었지만, `Images object`를 `export` 하고 있습니다.
`export { default as -- } from '--.png'` 와 같이 작성하면 바로 이미지 파일을 사용할 수 있습니다.

2022-04-01 06:43 UTC, hyejin30 commented on src/pages/SignUp.tsx
> +import {LabelInput} from '../components/LabelInput';
컴포넌트별로 폴더 생성 & index.tsx 만들어주고
index.ts에서 export 해주는 방식으로 변경했습니다~!
 
components
ㄴ index.ts
ㄴ GoBackButton
    ㄴ index.tsx
 
 ```
  // components/index.ts
 export {default as GoBackButton} from './GoBackButton';
 ```   
 ```
 // SignUp.tsx
 import {GoBackButton} from '~/components';
 ```

2022-04-01 06:45 UTC, hyejin30 commented on src/components/LabelPwInput.tsx
> +
삭제했습니다 짚어주셔서 감사합니다!

2022-04-01 06:51 UTC, hyejin30 commented on src/assets/images/index.ts
> +export default Images;
아래처럼 수정했습니다! 감사합니다
```
export {default as icBackArrow} from './ic-back-arrow.png';
export {default as icEyeOff} from './ic-eye-off.png';
export {default as icEyeOn} from './ic-eye-on.png';
```

2022-04-01 07:06 UTC, hyejin30 commented on src/config.ts
> +const baseUri: String = 'http://172.30.1.30:8080';
넵 별도로 관리하겠습니다!!

2022-04-04 01:48 UTC, jasonkang14 requested changes

2022-04-04 01:48 UTC, jasonkang14 commented on README.md
> +<<<<<<< HEAD
이거는 conflict네요. 
`README.md`라서 문제가 없는 것으로 나타나는 것이라서 수정 부탁 드립니다.

2022-04-04 01:48 UTC, jasonkang14 commented on package.json
> +    "v8-android-jit": "^9.93.0"
`v8-android-jit` 패키지의 목적은 무엇인가요?

2022-04-04 01:48 UTC, jasonkang14 commented on src/components/GoBackButton/index.tsx
> +const Button = styled.Pressable`
오 0.68에서 새로 나온 거군요. 하나 배워갑니다 👍
[TouchableOpacity](https://reactnative.dev/docs/touchableopacity)와는 어떤 차이점이 있나요?

2022-04-04 01:48 UTC, jasonkang14 commented on src/components/GoBackButton/index.tsx
> +  width: ${({theme}) => theme.fontSize.header};
굳굳

2022-04-04 01:48 UTC, jasonkang14 commented on src/components/LabelInput/index.tsx
> +        onChangeText={(text: string) => onChangeText(info, text)}
`onChange`와 `onChangeText`는 어떤 차이가 있나요?

2022-04-04 01:48 UTC, jasonkang14 commented on src/components/LabelPwInput/index.tsx
> +  info: string;
info는 어떤 값을 나타내나요?

2022-04-04 01:48 UTC, jasonkang14 commented on src/components/LabelPwInput/index.tsx
> +  const initialValue: IsPwNotShownProps = {
해당 값을 컴포넌트 안에서 설정하면, 상태가 바뀔때마다 계속해서 값을 할당하게 됩니다. 
상수는 컴포넌트 밖에서 선언하거나, 
```typescript
const [isPwNotShown, setIsPwNotShown] = useState({password: true, passwordVerfy: true})
```

로 수정해주세요

2022-04-04 01:48 UTC, jasonkang14 commented on src/components/LabelPwInput/index.tsx
> +  const initialValue: IsPwNotShownProps = {
변수명을 다시보면 state 이름이 비밀번호가 보이는지 보이지 않는지를 나타내기 때문에, 
상태를 따로 관리하는 것이 좋을 것 같습니다. 

일반적으로 하나의 state에 여러 값을 담는 경우는, 
동시에 state 여러개를 바꿔야 할 경우 render가 여러번 일어나지 않는 것을 방지하기 위함입니다. 
적절한 예는 아니지만 비밀번호를 입력할 때마다 `backgroundColor`를 바꾸면서 `TextInput`의 text도 바꾸고 비밀번호를 보였다가 안보였다가 변경한다는 경우 처럼요. 

지금 component state는 총3개정도 까지 생각할 수 있을 것 같습니다. 
1. 비밀번호가 보이는지 안보이는지
2. 비밀번호 형식이 맞는지

1번 state는 버튼으로 변경하고
2번 state는 비밀번호가 입력될 때 변경되니 
동시에 state를 바꿀 일은 없을 것 같습니다. 

가독성 향상을 위해서 state를 두개로 나누는 것이 더 좋을 것 같습니다.

2022-04-04 01:48 UTC, jasonkang14 commented on src/hooks/useSignUp.ts
> +      console.log(result);
PR에서 `console.log()`는 제거해주세요

2022-04-04 01:48 UTC, jasonkang14 commented on src/types/types.ts
> +export type UserInfoProps = {
아직 서버와 연동이 되지 않아서 일반 객체로 선언하신게 아니라면, 여기는 구체적으로 적어주는 것이 좋습니다.

2022-04-04 01:48 UTC, jasonkang14 commented on src/pages/SignUp.tsx
> +  const isButtonValid: boolean =
값을 선언하는 것보다 [useMemo](https://reactjs.org/docs/hooks-reference.html#usememo)를 사용하는 편이 더 좋을 것 같습니다.

2022-04-04 01:48 UTC, jasonkang14 commented on src/pages/SignUp.tsx
>  import {SignUpScreenProps} from 'types/types';
`types/types`는 파일명이 조금 더 구체적이면 좋을 것 같습니다.

2022-04-04 01:53 UTC, jasonkang14 commented on src/components/GoBackButton/index.tsx
> +const Button = styled.Pressable`
다시 찾아보니까 0.64에서 나온거군요 굳굳

2022-04-04 05:30 UTC, hyejin30 commented on src/components/GoBackButton/index.tsx
> +const Button = styled.Pressable`
저도 버튼 종류 찾아보다가 공식 문서에서 권장하는 걸 보고 썼는데,
더 다양한 유형의 Press 상호 작용을 감지할 수 있다고 합니다!

- hitSlop : 프레스가 감지될 수 있는 요소 외부의 추가 거리를 설정 (버튼 접근성 향상)
- hover, foucs, blur 기능을 포함하도록 확장 가능

Press API도 활용 해볼 수 있도록 좀 더 공부해보겠습니다!!

2022-04-04 05:39 UTC, hyejin30 commented on package.json
> +    "v8-android-jit": "^9.93.0"
react-native-debugger 설치 후
android 앱만 실행 되지 않고 바로 종료되는 문제가 있었는데, 
아래 글에서 v8-android-jit 패키지를 안내 해줘서 설치 후 문제를 해결했습니다.

https://bocoder.tistory.com/24
https://www.npmjs.com/package/react-native-v8

당시에는 문제 해결만 하고 바로 넘어갔었는데,
디버거와 해당 패키지 연관성을 더 생각해보겠습니다.!

2022-04-04 05:41 UTC, hyejin30 commented on src/hooks/useSignUp.ts
> +      console.log(result);
삭제했습니다! 주의하겠습니다

2022-04-04 05:54 UTC, hyejin30 commented on src/pages/SignUp.tsx
>  import {SignUpScreenProps} from 'types/types';
데이터 타입을 기재하는 것이라고 생각해서 dataTypes.ts 로 수정했습니다!

2022-04-04 05:55 UTC, hyejin30 commented on README.md
> +<<<<<<< HEAD
수정했습니다! 짚어주셔서 감사힙니다

2022-04-04 06:07 UTC, hyejin30 commented on src/components/LabelInput/index.tsx
> +        onChangeText={(text: string) => onChangeText(info, text)}
onChanage와 onChangeText는 모두 텍스트가 변경될 때 호출되는 콜백이지만
onChangeText가 더 단순화된 버전입니다!

onChange를 이용해 text를 변경하려면 event.nativeEvent.text로 접근해야하지만
onChangeText는 text로 값을 가져올 수 있습니다
해당 Input에 string 타입의 값만 들어와서, 더 사용이 간단한 onChangeText를 사용했습니다.

만약 타입이 다른 값이 들어오는 등 더 복잡한 로직이 필요할 경우
onChange를 사용할 계획입니다.
```
handleChange(event) {
    const {name, type, value} = event.nativeEvent;
    if(type==='text') {
        // code
    } else if (type==='number') {
        // code 
    }
    ...
}

```

2022-04-04 07:05 UTC, hyejin30 commented on src/config.ts
> +const baseUri: String = 'http://172.30.1.30:8080';
react-native-config 라이브러리 설치 후, 
.env 파일 생성하고 API_APP_KEY 변수를 만들었습니다.

config.js 파일은 아래처럼 수정했습니다.
```
import Config from 'react-native-config';

const baseUri: String = Config.API_APP_KEY;

export const fetchApi = {
  signIn: `${baseUri}/users/signin`,
  signUp: `${baseUri}/users/signup`,
};
```

2022-04-04 08:33 UTC, hyejin30 commented on src/components/LabelPwInput/index.tsx
> +  const initialValue: IsPwNotShownProps = {
상세하게 리뷰 남겨주셔서 감사합니다!
isPwNotShown state는 1번만 관리 할 수 있도록 아래처럼 수정했습니다.
```
// LabelPwInput/index.tsx

 const [isPwNotShown, setIsPwNotShown] = useState(true);
```
2번은 useSignUp.ts 에서 warningValid state에서 관리하게 했습니다.
isPwWarning - 비밀번호 형식이 맞는지
isPwVerifyWarning - 비밀번호 재입력 형식이 맞는지
```
// hooks/useSignUp.ts

  const [warningValid, setWarningValid] = useState({
    isFirstNameWarning: false,
    isLastNameWarning: false,
    isEmailWarning: false,
    isPwWarning: false,
    isPwVerifyWarning: false,
  });

```

2022-04-04 08:44 UTC, hyejin30 commented on src/types/types.ts
> +export type UserInfoProps = {
어떤 key, value가 들어오는지 구체적으로 명시했습니다!
이름도 SignUpInfoProps로 수정했습니다. 감사합니다

export type SignUpInfoProps = {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  passwordVerify: string;
};

2022-04-04 11:23 UTC, hyejin30 commented on src/pages/SignUp.tsx
> +  const isButtonValid: boolean =
useMemo를 활용해 state가 변할 때만 값이 할당 되도록 수정했습니다
- isButtonValid, warningText

+) signUpInfo, warningValid도 state가 변할 때만 할당되면 좋을 것 같아 함께 수정했는데,
 혹시 제가 잘못 이해해서 수정한 부분이 있다면 말씀 부탁드립니다!

```
  const {firstName, lastName, email, password, passwordVerify} = useMemo(
    () => signUpInfo,
    [signUpInfo],
  );

  const {
    isFirstNameWarning,
    isLastNameWarning,
    isEmailWarning,
    isPwWarning,
    isPwVerifyWarning,
  } = useMemo(() => warningValid, [warningValid]);

  const {
    firstNameWarningText,
    lastNameWarningText,
    emailWarningText,
    pwWarningText,
    pwVerifyWarningText,
  } = useMemo(() => warningText, [warningText]);

  const isButtonValid: boolean = useMemo(
    () => handleButtonValid(),
    [handleButtonValid],
  );
```
handleButtonValid 함수 : useSignUp에서 선언
```
  const handleButtonValid = () => {
    const {firstName, lastName, email} = signUpInfo;

    const valid: boolean =
      Boolean(
        firstName &&
          lastName &&
          email &&
          password &&
          passwordVerify &&
          password === passwordVerify,
      ) &&
      !isFirstNameWarning &&
      !isLastNameWarning &&
      !isEmailWarning &&
      !isPwWarning &&
      !isPwVerifyWarning;

    return valid;
  };
```

2022-04-04 13:52 UTC, jasonkang14 requested changes

2022-04-04 13:52 UTC, jasonkang14 commented on src/hooks/hooks.ts
> +    body = await response.json();
try문 안에서 response를 return하는게 더 깔끔해 보입니다.

2022-04-04 13:52 UTC, jasonkang14 commented on src/hooks/useSignUp.ts
> +        setWarningValid(prev => ({...prev, isEmailWarning: true}));
이런식으로 state가 두 번 변경되는 경우가 state를 하나로 관리해야 하는 경우입니다. render가 두 번 일어나기 때문입니다. 

코드를 다시 보니 
```typescript
 const [warningValid, setWarningValid] = useState({
    isFirstNameWarning: false,
    isLastNameWarning: false,
    isEmailWarning: false,
    isPwWarning: false,
    isPwVerifyWarning: false,
  });
```

이 변수들은 필요가 없을 것 같습니다. 
`warningText`의 초기값이 empty string인데, empty string은 falsy 한 값이기 때문입니다.
falsy한 값이니 `false`와 같은 역할을 할 수 있겠죠.

따라서 `warningText`가 falsy한 값이 아닐 경우에 `warningText`를 보여주는 식으로 변경한다면
`warningValid`에 해당하는 변수들이 필요없게 될 것 같습니다. 

특정 변수가 falsy한지 truthy한지 확인하기 위해서 
[!! operator](https://stackoverflow.com/a/29312197)를 사용합니다. 
불필요한 변수를 줄이고, state업데이트를 줄여서 더 효율적인 코드가 될 것 같습니다.

2022-04-04 13:52 UTC, jasonkang14 commented on src/components/GoBackButton/index.tsx
> +    <Button onPress={() => onPress(page)}>
navigation에는 `goBack()`이라는 method가 있습니다. 
[react-navigation 공식문서](https://reactnavigation.org/docs/use-navigation/#example)에 커스텀 헤더에서 어떻게 navigation을 활용해서 뒤로가기를 구현할 수 있는지 잘 나타나 있습니다. 
Header로 불필요한 prop을 넘겨주는 것을 방지할 수 있습니다.

2022-04-04 13:52 UTC, jasonkang14 commented on src/pages/SignUp.tsx
> +  const isButtonValid: boolean = useMemo(
이 변수를 제외하고는 굳이 `useMemo()`를 사용할 필요는 없을 것 같습니다. 
이 변수에 `useMemo()`사용을 권장한 이유는 해당 값이 여러 변수들의 조합으로 만들어지는 값이기 때문입니다.

2022-04-04 13:53 UTC, jasonkang14 commented on src/components/LabelInput/index.tsx
> +        onChangeText={(text: string) => onChangeText(info, text)}
`info`라는 이름으로 넘겨주는 prop이 결국 `name`또는 `target`과 같은 역할을 하는 것 같은데 그럼 차이가 없지 않나요?

2022-04-04 13:53 UTC, jasonkang14 commented on src/pages/SignUp.tsx
> +  const isButtonValid: boolean =
공식문서에서 expensive라고 불리는 함수를 따로 구현하신 점은 매우 좋습니다. 
하지만 `isButtonValid`를 제외하고는 굳이 useMemo()를 사용할 필요는 없을 것 같습니다.
이 변수에 useMemo()사용을 권장한 이유는 해당 값이 여러 변수들의 조합으로 만들어지는 값이기 때문입니다.

2022-04-05 01:42 UTC, jasonkang14 requested changes

2022-04-05 01:42 UTC, jasonkang14 commented on src/components/LabelInput/index.tsx
> +  name,
공식문서에 나온 property를 사용하셨군요 좋습니다 👍

2022-04-05 01:42 UTC, jasonkang14 commented on src/hooks/hooks.ts
> +    body = await response.json();
이렇게 된다면 try 문 밖에서 `body`라는 변수가 사용되지 않으니, lexical scope를 변경해주시는 것이 좋겠습니다.

2022-04-05 01:42 UTC, jasonkang14 commented on src/hooks/useSignUp.ts
> +  const [warnings, setWarnings] = useState({
text라는 변수를 빼니 조금 더 간결해지고 보기도 수월한 것 같네요. 좋습니다. 👍

2022-04-05 01:42 UTC, jasonkang14 commented on src/pages/SignUp.tsx
> +const LastNameView = styled.View`
`FirstNameView`와 `LastNameView`의 tag와 style 속성이 일치합니다. 
`styled-components`에서는 이런 경우에 `Class`의 상속과 유사하게 style을 상속받을 수 있습니다.
`styled-components`에서는 [extending styles](https://styled-components.com/docs/basics#extending-styles)라고 부르는데요, 참고해서 수정하면 좋을 것 같습니다.

2022-04-05 06:14 UTC, hyejin30 commented on src/hooks/useSignUp.ts
> +        setWarningValid(prev => ({...prev, isEmailWarning: true}));
감사합니다!! warningValid를 없애고, 
warningText를 warnings로 이름 변경 + !! operator를 활용해
- <WarningText> 렌더링 조건 
- 유효성 문구 
역할 2개를 다 할 수 있도록 수정했습니다. 상세하게 설명해주셔서 감사드립니다

2022-04-05 06:14 UTC, hyejin30 commented on src/pages/SignUp.tsx
> +  const isButtonValid: boolean = useMemo(
isButtonValid만 useMemo 사용하도록 수정했습니다!
여러 변수들의 조합으로 만들어질 경우 useMemo 사용하도록 하겠습니다!

2022-04-05 06:15 UTC, hyejin30 commented on src/components/GoBackButton/index.tsx
> +    <Button onPress={() => onPress(page)}>
감사합니다! goBackButton에서 prop 받지 않고,
goBack() method 활용하는 방식으로 수정했습니다

2022-04-05 06:22 UTC, hyejin30 commented on src/components/LabelInput/index.tsx
> +  name,
info 대신 어떤걸 쓸지 고민했었는데
되도록 공식 문서에 있는 property 사용하려고 했습니다 감사합니다 :) !!

2022-04-05 06:42 UTC, hyejin30 commented on src/hooks/hooks.ts
> +    body = await response.json();
try 문 밖에 있는 `let body;` 를 삭제하고 아래처럼 수정했습니다!
```
    const body = await response.json();
    return body;
```

2022-04-05 07:04 UTC, hyejin30 commented on src/pages/SignUp.tsx
> +const LastNameView = styled.View`
컴포넌트를 분리하지 않고 NameView 컴포넌트 1개만 만들었습니다!
style 상속 받아서 FirstNameView, LastNameView를 만들까 생각 했었는데
상속 받지 않고 NameView만 공통으로 사용하기로 했습니다.
감사합니다!

```
const NameView = styled.View`
  flex: 1;
  margin-right: 5px;
`;
```
```
  <NameView>
      <LabelInput
        label="성"
        name="firstName"
        value={firstName}
        placeholder="성을 입력해주세요"
        onChangeText={updateSignUpInfo}
        onBlur={checkSignUpInfo}
      />
      {!!firstNameWarning && (
        <WarningText>{firstNameWarning}</WarningText>
      )}
</NameView>
<NameView>
      <LabelInput
        label="이름"
        name="lastName"
        value={lastName}
        placeholder="이름을 입력해주세요"
        onChangeText={updateSignUpInfo}
        onBlur={checkSignUpInfo}
      />
      {!!lastNameWarning && (
        <WarningText>{lastNameWarning ?? ''}</WarningText>
      )}
</NameView>
```

2022-04-05 07:51 UTC, jasonkang14 approved these changes
LGTM

2022-04-05 07:56 UTC, merged