[김혜진] Entry UI, 기능 구현
hyejin30/WebRTC-APPLICATION-Frontend pull request #6
Opened 2022-04-06 07:20 UTC by hyejin30

## :: 구현 목표 
- 엔트리 페이지 UI 구현
- SignIn, SignUp 페이지 이동 기능 구현
- navigation 수정 : RootStackParamList, NativeStackScreenProps 활용

<br />

## :: 구현 사항 설명

### 1. 엔트리 페이지 UI
1-1) 아래 디바이스를 기준으로 작업
* android : Pixel 3
* ios : iPhone 13

<br />

1-2) 레이아웃
- ContainerView를 2개의 View(LogoView, View)로 구분하고
   LogoView에서 로고 중앙 정렬.

1-3) 버튼 스타일링
- 로그인 버튼 : StyledButton 공통 컴포넌트 사용
- 회원가입 버튼 : Entry.tsx 파일 내에 `SignUpButton` 컴포넌트를 별도로 만들었음.
ㄴ StyledButton 공통 컴포넌트에서 색상을 지정 해놔서 `(배경색 primary, 폰트 white)` 다른 색으로 변경하기 어려웠음.
ㄴ 추후 StyledButton 컴포넌트에 color, background-color를 prop으로 내려줘서 버튼색도 커스텀 가능하도록 변경해볼 예정임.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/98295004/161915813-b9c9fe10-4991-4c3c-9fc3-7b8eb43c845f.png">

<br />

### 2. 기능 구현
2-1)  페이지 이동
- 로그인 버튼 : 누르면 signIn으로 이동
- 회원가입 버튼 : 누르면 signUp으로 이동

<br />

2-2) navigation 수정
- Entry 페이지만 RootStackParamList type을 사용하고, 그 외 페이지는 ParamListBase를 사용하고 있었음
-> [공식 문서](https://reactnavigation.org/docs/5.x/typescript/) 를 참고하여, 모든 페이지가 RootStackParamList type을 사용하도록 변경함. 
-> 참고한 코드
```
import { StackNavigationProp } from '@react-navigation/stack';

type ProfileScreenNavigationProp = StackNavigationProp<
  RootStackParamList,
  'Profile'
>;

type Props = {
  navigation: ProfileScreenNavigationProp;
};
```

## :: 기타 질문 및 특이 사항

없음

2022-04-06 07:27 UTC, jasonkang14 commented on src/App.tsx
> +import {RootStackParamList} from './types/dataTypes';
굳굳 좋습니다

2022-04-06 07:27 UTC, jasonkang14 commented on src/pages/SignIn.tsx
> +    page => {
갑자기 린트가 변경된 걸까요? 소괄호가 빠지는 이유가 궁금합니다.

2022-04-06 17:21 UTC, hyejin30 commented on src/pages/SignIn.tsx
> +    page => {
page의 타입 지정을 하지 않는 쪽으로 변경해서 자동으로 소괄호가 빠졌는데,
다시 타입을 string으로 지정하게 되어 소괄호를 추가 했습니다.

*  왜 page 타입 지정을 안했는지
  - SignInScreenProps를 ParamListBase > RootStackParamList로 변경하면서,
     changePage에서 string 형식을 할당할 수 없다는 오류가 발생했습니다.
     page의 type을 지정하지 않으니 (any) 오류가 해결 되었는데요
   
```
export type SignInScreenProps = NativeStackScreenProps<
  RootStackParamList,
  'Entry'
>;
```
![image](https://user-images.githubusercontent.com/98295004/162026829-c1bc5167-d761-4546-b897-37c99274dbfa.png)

* ParamaListBase를 사용하면 navigation.navigate에서
   string 형식의 파라미터를 사용할 수 있어서,
   RootStackParamList > ParamListBase로 다시 수정했습니다.
```
export type EntryScreenProps = NativeStackScreenProps<
   ParamListBase,
  'Entry'
>;
```

* RootStackParamList로 Screen 컴포넌트 Props의 타입을 검증하려고 했는데,
  위와 같은 에러가 생겨서, ParamListBase를 사용했습니다.
  이러한 에러를 해결하면서 page 파라미터의 형식에 잠시 변경이 있었습니다.
  지금은 page: string으로 다시 타입 지정했습니다!

2022-04-07 02:37 UTC, jasonkang14 requested changes

2022-04-07 02:37 UTC, jasonkang14 commented on src/pages/Entry.tsx
> +  const changePage = (page: string) => {
놓쳤던 부분인데 react native에서는 `page`보다는 `screen`이라는 변수명을 사용합니다! 위에 작성하신 `EntryScreenProps` 처럼요. 수정 부탁 드립니다

2022-04-07 02:37 UTC, jasonkang14 commented on src/pages/Entry.tsx
> +  const changePage = (page: string) => {
그리고 혹시 `navigation.navigate()`에서 빨간줄 그어지지 않나요? string을 screen네임으로 쓸 수 없다는 식으로. 
`navigate()` method에 들어가는 parameter도 선언한 스크린중에 하나로만 될 수 있도록 작업되면 좋을 것 같습니다!

2022-04-07 02:38 UTC, jasonkang14 commented on src/pages/Entry.tsx
> +  const changePage = (page: string) => {
`useCallback()`은 말씀하신 것처럼 prop으로 넘어오는 변수를 사용할 때 유용하긴 합니다! 하지만 말씀하신 것처럼 지금 상황에서는 꼭 필요하진 않은 것 같네요. 고생하셨습니다!

2022-04-12 01:02 UTC, hyejin30 commented on src/pages/Entry.tsx
> +  const changePage = (page: string) => {
코멘트 감사드립니다!
changeScreen parameter를 선언한 스크린 중에 하나로만 쓸 수 있게 변경 했습니다
(모든 screen의 changeScreen 함수 아래처럼 수정)
```
  const changeScreen = (screen: keyof RootStackParamList) => {
    navigation.navigate(screen);
  };
```

2022-04-12 04:39 UTC, jasonkang14 approved these changes
LGTM

2022-04-12 04:39 UTC, jasonkang14 commented on src/screens/Entry.tsx
> +  const changeScreen = (screen: keyof RootStackParamList) => {
굳굳 좋습니다

2022-04-12 04:39 UTC, merged

2022-04-12 04:41 UTC, jasonkang14 commented
` < 이거 3개 사용하실 때 옆에 언어를 쓰면, 포맷에 맞게 컬러링(?)을 해줍니다.


```typescript
const Stack = createNativeStackNavigator<RootStackParamList>();
```

<img width="503" alt="Screen Shot 2022-04-12 at 1 41 21 PM" src="https://user-images.githubusercontent.com/45306565/162882092-266c92d6-f778-42f4-8f84-b129790b7d36.png">

2022-04-12 07:37 UTC, hyejin30 commented
감사합니다!! 댓글 남길 때 활용하겠습니다 :)