[김혜진] VideoChat - 영상 연결, 비디오 전환, 비디오/오디오 MUTE 구현
hyejin30/WebRTC-APPLICATION-Frontend pull request #8
Opened 2022-04-15 04:34 UTC by hyejin30

## :: 구현 목표 
- 화상 연결 스크린 UI 추가 작업 
- webSocket, webRTC를 이용해 2인 영상 연결 기능 구현
- 비디오 전환 기능 구현
- 비디오, 오디오 mute 기능 구현
<br />

## :: 구현 사항 설명

### 1. 화상 연결 스크린 UI
1-1) 아래 디바이스를 기준으로 작업
* android : Galaxy s21+
* ios : iPhone 13

<br />

1-2) 추가 작업 내용
- 콜러, 콜리 이름 표시
ㄴ *(구현 예정) 백엔드와 통신해서 유저의 실제 이름을 표시할 예정입니다*

- 오디오, 비디오 ON/OFF 이미지 추가
ㄴ 버튼을 누르면 이미지가 변경되도록 함
ㄴ 비디오 MUTE : 내 영상이 프로필 이미지로 전환
ㄴ 오디오 MUTE : 내 이름 옆에 오디오 아이콘 표시

<br />

<img width="645" alt="image" src="https://user-images.githubusercontent.com/98295004/163516741-94bfd6da-4741-4f73-ae67-339c7780f062.png">

<br />

### 2. 기능 구현
2-1)  2인 영상 연결
- 순서 : websocket, peerConnection 생성 -> getMedia -> makeConnection -> 8초 후 sendOffer를 호출하는 순서로 구성
- getMedia
ㄴ 로컬 비디오, 오디오 : localStream 스테이트에 저장하고, peerConnection 로컬 스트림에 추가
- makeConnection
ㄴ peerConnection, webSocket 이벤트 핸들러 등록
- sendOffer
ㄴ 상대방이 웹소켓 서버와 바로 연결되지 못했을 때를 고려해서 8초 후 offer를 보냄
ㄴ *(구현 예정) 렌더링 후 8초 뒤에 보내는 것이 아니라, 상대방이 연결된 것을 감지해서 offer를 보내도록 수정할 예정입니다.*
    - 
<br />

2-2) 비디오 전환
- 비디오 전환 버튼을 누르면 facingMode를 변경할 수 있도록 함 (user, environment)
- isVideoFront 스테이트가 변경되면, initCall을 호출하여 리렌더링 됨

<br />

2-3) 비디오, 오디오 MUTE
- 각각의 MUTE을 누르면 아이콘 이미지가 전환되고, initCall을 호출함
- 비디오 MUTE 시, 내 화면은 프로필 이미지로 변경되고 상대방의 화면은 검은 화면으로 변함

## :: 기타 질문 및 특이 사항

[궁금한 점]
1. webSocket, peerConnection 1개만 생성 되는게 맞을지
peerConnection이 1개만 생성되어야 한다고 생각했는데, 앱을 실행하면 여러개가 생성됩니다.
여러번 실행하지 않으려고 useMySocket 함수 외부에 변수를 선언했는데도 여러개가 생성되는데,
원래 webSocket, peerConnection은 1개만 생성되어야 하는건지 궁금합니다!

![image](https://user-images.githubusercontent.com/98295004/163518824-cb8b7107-7de0-46c5-afd4-865ecd39788f.png)

<br />

[특이 사항]
기능 구현 후 여러 이슈가 있어 수정할 예정입니다.

1) 내 음성이 내 디바이스에서 들리는 문제

2) 8초 후 sendOffer를 호출하는 점 때문에 비디오 전환, MUTE를 하면 상대방 화면에서 8초 후 반영되는 문제

3) .env 에러
.env 기능에서 에러가 발생해서 서버 주소들을 외부에 노출시켜 놨습니다.
다시 주소를 숨길 수 있도록 수정할 예정입니다.

4) warning 발생
ㄴ 이전에 알려주신 공식문서 참고해서 수정할 예정입니다.
https://www.w3.org/TR/webrtc/#rtcsignalingstate-enum
![image](https://user-images.githubusercontent.com/98295004/163518586-2d09ae22-9ca7-4b7e-b0ed-4faca5862ed2.png)

2022-04-15 04:59 UTC, jasonkang14 requested changes

2022-04-15 04:59 UTC, jasonkang14 commented on src/hooks/useMySocket/index.ts
> +const TURN_SERVER = 'turn:54.180.143.248';
상수들은 `.env` 파일에서 환경변수로 관리하는 것이 좋습니다.

2022-04-15 04:59 UTC, jasonkang14 commented on src/hooks/useMySocket/index.ts
> +          (async (answer: RTCSessionDescription) => {
`await` 하지 않는 경우에는 `async`를 제거해주세요

2022-04-15 04:59 UTC, jasonkang14 commented on src/hooks/useMySocket/index.ts
> +    setTimeout(() => sendOffer(), 8000);
8초를 기다리는 이유가 `getMedia()`, `makeConnection()` 이 완료되기를 기다리는 거라면 완료되었다는 별도의 상태값을 가지고 있는게 더 좋을 것 같습니다.

2022-04-15 04:59 UTC, jasonkang14 commented on src/hooks/useMySocket/index.ts
> +  }, [isVideoFront, isVideo, isAudio]);
이러면 카메라를 전환하거나, 영상이나 음성 상태가 변경될때마다 `initCall()`이 실행될 것 같습니다. `initCall()`이 한 번만 실행되는 방향으로 수정해주세요

2022-04-15 05:01 UTC, jasonkang14 commented
1. webSocket, peerConnection 변수 선언 위치
다시 새로 만들 필요가 없다고 생각해서, useMySocket 외부에 선언했는데
외부에 선언하는 게 맞을지 궁금했습니다!

component 안에서 생성해도 다시 만들어지지 않도록 설정할 수 있습니다.
[useRef](https://reactjs.org/docs/hooks-reference.html#useref)를 참고해주세요

2022-04-15 08:45 UTC, hyejin30 commented on src/hooks/useMySocket/index.ts
> +          (async (answer: RTCSessionDescription) => {
제거 했습니다! 감사합니다

2022-04-19 06:34 UTC, hyejin30 commented on src/hooks/useMySocket/index.ts
> +const TURN_SERVER = 'turn:54.180.143.248';
.env 파일에서 환경변수로 관리하도록 수정했습니다! 감사합니다

2022-04-20 00:41 UTC, hyejin30 commented on src/hooks/useMySocket/index.ts
> +  }, [isVideoFront, isVideo, isAudio]);
`initCall`은 렌더링 이후 1번만 실행하고, 영상이나 음성 상태가 변경될 때마다 `getMedia`가 실행되도록 수정했습니다
```typescript
  useEffect(() => {
    initCall();
  }, []);

  useEffect(() => {
    getMedia();
  }, [isVideoFront, isVideo, isAudio]);

```

2022-04-20 00:43 UTC, hyejin30 commented
websocket, peerconnection은 `useRef`를 이용해 useSocket 안에 선언했습니다
useRef 로 관리하는 변수는 값이 변경되어도 컴포넌트가 리렌더링되지 않는다는 것을 알았습니다. 감사합니다!

```typescript

const useMySocket = () => {
  const ws = useRef(new WebSocket(SOCKET_SERVER));
  const pc = useRef(new RTCPeerConnection(configuration));
  ...
  }
```

2022-04-20 00:47 UTC, hyejin30 commented on src/hooks/useMySocket/index.ts
> +    setTimeout(() => sendOffer(), 8000);
동기로 처리되는 `makeConnection()`은 그대로 두고, 비동기 작업이 이루어지는 `getMedia()` 앞에 await를 붙여서
완료 후에 `sendOffer()`가 실행되도록 했습니다. 
```typescript
  const initCall = async () => {
    await getMedia();
    makeConnection();
    sendOffer();
  };
```

2022-04-20 02:32 UTC, jasonkang14 approved these changes
LGTM

2022-04-20 02:32 UTC, merged